name: CI

on:
  push:
  pull_request:
#  schedule:
#    - cron: '9 * * * *'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate HTML

    steps:
    - name: Generate HTML
      env:
         PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        curl -X POST \
             -H "Authorization: token $PERSONAL_ACCESS_TOKEN" \
             -H "Accept: application/vnd.github.v3+json" \
             https://api.github.com/repos/kantoniko/kantoniko.github.io/actions/workflows/ci.yml/dispatches \
             -d '{"ref":"main"}' | tee out.txt
        if [ -s out.txt ]
        then
            exit 1
        else
            exit 0
        fi


